---
# CNN training example
seed: 42

label_transform:
  strategy: sqrt

data:
  dataset_file: npy_data/generated_trees.npy
  batch_size: 32
  num_workers: 0
  train_ratio: 0.70
  val_ratio: 0.15

trainer:
  epochs: 20
  patience: 10
  learning_rate: 0.001
  weight_decay: 0.0

model:
  in_channels: 4
  rooted: true
  num_outputs: 3
  topology_classification: false
  topology_weight: 1.0

outputs:
  results_dir: branch_plots/sample_run
  zoomed_plots: true
  individual_branch_plots: true
  branch_sum_plots: true

---
# KAN training example
seed: 99

label_transform:
  strategy: log

data:
  dataset_file: npy_data/three_taxa_example.npy
  batch_size: 32
  num_workers: 0
  train_ratio: 0.75
  val_ratio: 0.15

trainer:
  epochs: 40
  patience: 12
  learning_rate: 0.0003
  weight_decay: 0.0

model:
  in_channels: 5
  rooted: false
  num_outputs: 4
  topology_classification: false
  topology_weight: 1.0
  kan:
    hidden_layers: [512, 256, 128]
    grid: 7
    spline_order: 3
    mult_arity: 2
    noise_scale: 0.2
    base_function: silu
    symbolic_enabled: false
    sparse_init: false
    auto_save: false
    grid_eps: 0.05
    grid_range: [-1.0, 1.0]

outputs:
  results_dir: results/kan_example
  zoomed_plots: false
  individual_branch_plots: false
  branch_sum_plots: false
